/*
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 14.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.precisely.apis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.precisely.apis.model.CandidateRange;
import com.precisely.apis.model.FieldsMatching;
import com.precisely.apis.model.GeoPos;
import com.precisely.apis.model.GeocodeAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Candidate
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-02-17T17:59:08.288488200+05:30[Asia/Calcutta]")
public class Candidate {
  public static final String SERIALIZED_NAME_PRECISION_LEVEL = "precisionLevel";
  @SerializedName(SERIALIZED_NAME_PRECISION_LEVEL)
  private Integer precisionLevel;

  public static final String SERIALIZED_NAME_FORMATTED_STREET_ADDRESS = "formattedStreetAddress";
  @SerializedName(SERIALIZED_NAME_FORMATTED_STREET_ADDRESS)
  private String formattedStreetAddress;

  public static final String SERIALIZED_NAME_FORMATTED_LOCATION_ADDRESS = "formattedLocationAddress";
  @SerializedName(SERIALIZED_NAME_FORMATTED_LOCATION_ADDRESS)
  private String formattedLocationAddress;

  public static final String SERIALIZED_NAME_IDENTIFIER = "identifier";
  @SerializedName(SERIALIZED_NAME_IDENTIFIER)
  private String identifier;

  public static final String SERIALIZED_NAME_PRECISION_CODE = "precisionCode";
  @SerializedName(SERIALIZED_NAME_PRECISION_CODE)
  private String precisionCode;

  public static final String SERIALIZED_NAME_SOURCE_DICTIONARY = "sourceDictionary";
  @SerializedName(SERIALIZED_NAME_SOURCE_DICTIONARY)
  private String sourceDictionary;

  public static final String SERIALIZED_NAME_MATCHING = "matching";
  @SerializedName(SERIALIZED_NAME_MATCHING)
  private FieldsMatching matching;

  public static final String SERIALIZED_NAME_GEOMETRY = "geometry";
  @SerializedName(SERIALIZED_NAME_GEOMETRY)
  private GeoPos geometry;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private GeocodeAddress address;

  public static final String SERIALIZED_NAME_RANGES = "ranges";
  @SerializedName(SERIALIZED_NAME_RANGES)
  private List<CandidateRange> ranges = null;

  public Candidate() { 
  }

  public Candidate precisionLevel(Integer precisionLevel) {
    
    this.precisionLevel = precisionLevel;
    return this;
  }

   /**
   * Get precisionLevel
   * @return precisionLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPrecisionLevel() {
    return precisionLevel;
  }


  public void setPrecisionLevel(Integer precisionLevel) {
    this.precisionLevel = precisionLevel;
  }


  public Candidate formattedStreetAddress(String formattedStreetAddress) {
    
    this.formattedStreetAddress = formattedStreetAddress;
    return this;
  }

   /**
   * Get formattedStreetAddress
   * @return formattedStreetAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFormattedStreetAddress() {
    return formattedStreetAddress;
  }


  public void setFormattedStreetAddress(String formattedStreetAddress) {
    this.formattedStreetAddress = formattedStreetAddress;
  }


  public Candidate formattedLocationAddress(String formattedLocationAddress) {
    
    this.formattedLocationAddress = formattedLocationAddress;
    return this;
  }

   /**
   * Get formattedLocationAddress
   * @return formattedLocationAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFormattedLocationAddress() {
    return formattedLocationAddress;
  }


  public void setFormattedLocationAddress(String formattedLocationAddress) {
    this.formattedLocationAddress = formattedLocationAddress;
  }


  public Candidate identifier(String identifier) {
    
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIdentifier() {
    return identifier;
  }


  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }


  public Candidate precisionCode(String precisionCode) {
    
    this.precisionCode = precisionCode;
    return this;
  }

   /**
   * Get precisionCode
   * @return precisionCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPrecisionCode() {
    return precisionCode;
  }


  public void setPrecisionCode(String precisionCode) {
    this.precisionCode = precisionCode;
  }


  public Candidate sourceDictionary(String sourceDictionary) {
    
    this.sourceDictionary = sourceDictionary;
    return this;
  }

   /**
   * Get sourceDictionary
   * @return sourceDictionary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSourceDictionary() {
    return sourceDictionary;
  }


  public void setSourceDictionary(String sourceDictionary) {
    this.sourceDictionary = sourceDictionary;
  }


  public Candidate matching(FieldsMatching matching) {
    
    this.matching = matching;
    return this;
  }

   /**
   * Get matching
   * @return matching
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FieldsMatching getMatching() {
    return matching;
  }


  public void setMatching(FieldsMatching matching) {
    this.matching = matching;
  }


  public Candidate geometry(GeoPos geometry) {
    
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeoPos getGeometry() {
    return geometry;
  }


  public void setGeometry(GeoPos geometry) {
    this.geometry = geometry;
  }


  public Candidate address(GeocodeAddress address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GeocodeAddress getAddress() {
    return address;
  }


  public void setAddress(GeocodeAddress address) {
    this.address = address;
  }


  public Candidate ranges(List<CandidateRange> ranges) {
    
    this.ranges = ranges;
    return this;
  }

  public Candidate addRangesItem(CandidateRange rangesItem) {
    if (this.ranges == null) {
      this.ranges = new ArrayList<CandidateRange>();
    }
    this.ranges.add(rangesItem);
    return this;
  }

   /**
   * Get ranges
   * @return ranges
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<CandidateRange> getRanges() {
    return ranges;
  }


  public void setRanges(List<CandidateRange> ranges) {
    this.ranges = ranges;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Candidate candidate = (Candidate) o;
    return Objects.equals(this.precisionLevel, candidate.precisionLevel) &&
        Objects.equals(this.formattedStreetAddress, candidate.formattedStreetAddress) &&
        Objects.equals(this.formattedLocationAddress, candidate.formattedLocationAddress) &&
        Objects.equals(this.identifier, candidate.identifier) &&
        Objects.equals(this.precisionCode, candidate.precisionCode) &&
        Objects.equals(this.sourceDictionary, candidate.sourceDictionary) &&
        Objects.equals(this.matching, candidate.matching) &&
        Objects.equals(this.geometry, candidate.geometry) &&
        Objects.equals(this.address, candidate.address) &&
        Objects.equals(this.ranges, candidate.ranges);
  }

  @Override
  public int hashCode() {
    return Objects.hash(precisionLevel, formattedStreetAddress, formattedLocationAddress, identifier, precisionCode, sourceDictionary, matching, geometry, address, ranges);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Candidate {\n");
    sb.append("    precisionLevel: ").append(toIndentedString(precisionLevel)).append("\n");
    sb.append("    formattedStreetAddress: ").append(toIndentedString(formattedStreetAddress)).append("\n");
    sb.append("    formattedLocationAddress: ").append(toIndentedString(formattedLocationAddress)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    precisionCode: ").append(toIndentedString(precisionCode)).append("\n");
    sb.append("    sourceDictionary: ").append(toIndentedString(sourceDictionary)).append("\n");
    sb.append("    matching: ").append(toIndentedString(matching)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    ranges: ").append(toIndentedString(ranges)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

