/*
 * Precisely APIs
 * Enhance & enrich your data, applications, business processes, and workflows with rich location, information, and identify APIs.
 *
 * The version of the OpenAPI document: 17.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.precisely.apis.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.precisely.apis.model.GetPostalCodesAPIOutputUserFields;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ValidateMailingAddressPremiumOutput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-14T13:16:01.386923100+05:30[Asia/Calcutta]")
public class ValidateMailingAddressPremiumOutput {
  public static final String SERIALIZED_NAME_USER_FIELDS = "user_fields";
  @SerializedName(SERIALIZED_NAME_USER_FIELDS)
  private List<GetPostalCodesAPIOutputUserFields> userFields = null;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATUS_CODE = "Status.Code";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private String statusCode;

  public static final String SERIALIZED_NAME_STATUS_DESCRIPTION = "Status.Description";
  @SerializedName(SERIALIZED_NAME_STATUS_DESCRIPTION)
  private String statusDescription;

  public static final String SERIALIZED_NAME_CONFIDENCE = "Confidence";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE)
  private String confidence;

  public static final String SERIALIZED_NAME_RECORD_TYPE = "RecordType";
  @SerializedName(SERIALIZED_NAME_RECORD_TYPE)
  private String recordType;

  public static final String SERIALIZED_NAME_RECORD_TYPE_DEFAULT = "RecordType.Default";
  @SerializedName(SERIALIZED_NAME_RECORD_TYPE_DEFAULT)
  private String recordTypeDefault;

  public static final String SERIALIZED_NAME_MULTIPLE_MATCHES = "MultipleMatches";
  @SerializedName(SERIALIZED_NAME_MULTIPLE_MATCHES)
  private String multipleMatches;

  public static final String SERIALIZED_NAME_COULD_NOT_VALIDATE = "CouldNotValidate";
  @SerializedName(SERIALIZED_NAME_COULD_NOT_VALIDATE)
  private String couldNotValidate;

  public static final String SERIALIZED_NAME_COUNTRY_LEVEL = "CountryLevel";
  @SerializedName(SERIALIZED_NAME_COUNTRY_LEVEL)
  private String countryLevel;

  public static final String SERIALIZED_NAME_ADDRESS_FORMAT = "AddressFormat";
  @SerializedName(SERIALIZED_NAME_ADDRESS_FORMAT)
  private String addressFormat;

  public static final String SERIALIZED_NAME_ADDRESS_LINE1 = "AddressLine1";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE1)
  private String addressLine1;

  public static final String SERIALIZED_NAME_ADDRESS_LINE2 = "AddressLine2";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE2)
  private String addressLine2;

  public static final String SERIALIZED_NAME_ADDRESS_LINE3 = "AddressLine3";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE3)
  private String addressLine3;

  public static final String SERIALIZED_NAME_ADDRESS_LINE4 = "AddressLine4";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE4)
  private String addressLine4;

  public static final String SERIALIZED_NAME_CITY = "City";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_STATE_PROVINCE = "StateProvince";
  @SerializedName(SERIALIZED_NAME_STATE_PROVINCE)
  private String stateProvince;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "PostalCode";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public static final String SERIALIZED_NAME_POSTAL_CODE_BASE = "PostalCode.Base";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_BASE)
  private String postalCodeBase;

  public static final String SERIALIZED_NAME_POSTAL_CODE_ADD_ON = "PostalCode.AddOn";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_ADD_ON)
  private String postalCodeAddOn;

  public static final String SERIALIZED_NAME_COUNTRY = "Country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_ADDITIONAL_INPUT_DATA = "AdditionalInputData";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_INPUT_DATA)
  private String additionalInputData;

  public static final String SERIALIZED_NAME_FIRM_NAME = "FirmName";
  @SerializedName(SERIALIZED_NAME_FIRM_NAME)
  private String firmName;

  public static final String SERIALIZED_NAME_HOUSE_NUMBER = "HouseNumber";
  @SerializedName(SERIALIZED_NAME_HOUSE_NUMBER)
  private String houseNumber;

  public static final String SERIALIZED_NAME_LEADING_DIRECTIONAL = "LeadingDirectional";
  @SerializedName(SERIALIZED_NAME_LEADING_DIRECTIONAL)
  private String leadingDirectional;

  public static final String SERIALIZED_NAME_STREET_NAME = "StreetName";
  @SerializedName(SERIALIZED_NAME_STREET_NAME)
  private String streetName;

  public static final String SERIALIZED_NAME_STREET_SUFFIX = "StreetSuffix";
  @SerializedName(SERIALIZED_NAME_STREET_SUFFIX)
  private String streetSuffix;

  public static final String SERIALIZED_NAME_TRAILING_DIRECTIONAL = "TrailingDirectional";
  @SerializedName(SERIALIZED_NAME_TRAILING_DIRECTIONAL)
  private String trailingDirectional;

  public static final String SERIALIZED_NAME_APARTMENT_LABEL = "ApartmentLabel";
  @SerializedName(SERIALIZED_NAME_APARTMENT_LABEL)
  private String apartmentLabel;

  public static final String SERIALIZED_NAME_APARTMENT_NUMBER = "ApartmentNumber";
  @SerializedName(SERIALIZED_NAME_APARTMENT_NUMBER)
  private String apartmentNumber;

  public static final String SERIALIZED_NAME_APARTMENT_LABEL2 = "ApartmentLabel2";
  @SerializedName(SERIALIZED_NAME_APARTMENT_LABEL2)
  private String apartmentLabel2;

  public static final String SERIALIZED_NAME_APARTMENT_NUMBER2 = "ApartmentNumber2";
  @SerializedName(SERIALIZED_NAME_APARTMENT_NUMBER2)
  private String apartmentNumber2;

  public static final String SERIALIZED_NAME_R_R_H_C = "RRHC";
  @SerializedName(SERIALIZED_NAME_R_R_H_C)
  private String RRHC;

  public static final String SERIALIZED_NAME_PO_BOX = "POBox";
  @SerializedName(SERIALIZED_NAME_PO_BOX)
  private String poBox;

  public static final String SERIALIZED_NAME_PRIVATE_MAILBOX = "PrivateMailbox";
  @SerializedName(SERIALIZED_NAME_PRIVATE_MAILBOX)
  private String privateMailbox;

  public static final String SERIALIZED_NAME_PRIVATE_MAILBOX_TYPE = "PrivateMailbox.Type";
  @SerializedName(SERIALIZED_NAME_PRIVATE_MAILBOX_TYPE)
  private String privateMailboxType;

  public static final String SERIALIZED_NAME_HOUSE_NUMBER_INPUT = "HouseNumber.Input";
  @SerializedName(SERIALIZED_NAME_HOUSE_NUMBER_INPUT)
  private String houseNumberInput;

  public static final String SERIALIZED_NAME_LEADING_DIRECTIONAL_INPUT = "LeadingDirectional.Input";
  @SerializedName(SERIALIZED_NAME_LEADING_DIRECTIONAL_INPUT)
  private String leadingDirectionalInput;

  public static final String SERIALIZED_NAME_STREET_NAME_INPUT = "StreetName.Input";
  @SerializedName(SERIALIZED_NAME_STREET_NAME_INPUT)
  private String streetNameInput;

  public static final String SERIALIZED_NAME_STREET_SUFFIX_INPUT = "StreetSuffix.Input";
  @SerializedName(SERIALIZED_NAME_STREET_SUFFIX_INPUT)
  private String streetSuffixInput;

  public static final String SERIALIZED_NAME_TRAILING_DIRECTIONAL_INPUT = "TrailingDirectional.Input";
  @SerializedName(SERIALIZED_NAME_TRAILING_DIRECTIONAL_INPUT)
  private String trailingDirectionalInput;

  public static final String SERIALIZED_NAME_APARTMENT_LABEL_INPUT = "ApartmentLabel.Input";
  @SerializedName(SERIALIZED_NAME_APARTMENT_LABEL_INPUT)
  private String apartmentLabelInput;

  public static final String SERIALIZED_NAME_APARTMENT_NUMBER_INPUT = "ApartmentNumber.Input";
  @SerializedName(SERIALIZED_NAME_APARTMENT_NUMBER_INPUT)
  private String apartmentNumberInput;

  public static final String SERIALIZED_NAME_RR_H_C_INPUT = "RRHC.Input";
  @SerializedName(SERIALIZED_NAME_RR_H_C_INPUT)
  private String rrHCInput;

  public static final String SERIALIZED_NAME_PO_BOX_INPUT = "POBox.Input";
  @SerializedName(SERIALIZED_NAME_PO_BOX_INPUT)
  private String poBoxInput;

  public static final String SERIALIZED_NAME_PRIVATE_MAILBOX_INPUT = "PrivateMailbox.Input";
  @SerializedName(SERIALIZED_NAME_PRIVATE_MAILBOX_INPUT)
  private String privateMailboxInput;

  public static final String SERIALIZED_NAME_PRIVATE_MAILBOX_TYPE_INPUT = "PrivateMailbox.Type.Input";
  @SerializedName(SERIALIZED_NAME_PRIVATE_MAILBOX_TYPE_INPUT)
  private String privateMailboxTypeInput;

  public static final String SERIALIZED_NAME_CITY_INPUT = "City.Input";
  @SerializedName(SERIALIZED_NAME_CITY_INPUT)
  private String cityInput;

  public static final String SERIALIZED_NAME_STATE_PROVINCE_INPUT = "StateProvince.Input";
  @SerializedName(SERIALIZED_NAME_STATE_PROVINCE_INPUT)
  private String stateProvinceInput;

  public static final String SERIALIZED_NAME_POSTAL_CODE_INPUT = "PostalCode.Input";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_INPUT)
  private String postalCodeInput;

  public static final String SERIALIZED_NAME_COUNTRY_INPUT = "Country.Input";
  @SerializedName(SERIALIZED_NAME_COUNTRY_INPUT)
  private String countryInput;

  public static final String SERIALIZED_NAME_FIRM_NAME_INPUT = "FirmName.Input";
  @SerializedName(SERIALIZED_NAME_FIRM_NAME_INPUT)
  private String firmNameInput;

  public static final String SERIALIZED_NAME_HOUSE_NUMBER_RESULT = "HouseNumber.Result";
  @SerializedName(SERIALIZED_NAME_HOUSE_NUMBER_RESULT)
  private String houseNumberResult;

  public static final String SERIALIZED_NAME_LEADING_DIRECTIONAL_RESULT = "LeadingDirectional.Result";
  @SerializedName(SERIALIZED_NAME_LEADING_DIRECTIONAL_RESULT)
  private String leadingDirectionalResult;

  public static final String SERIALIZED_NAME_STREET_RESULT = "Street.Result";
  @SerializedName(SERIALIZED_NAME_STREET_RESULT)
  private String streetResult;

  public static final String SERIALIZED_NAME_STREET_NAME_RESULT = "StreetName.Result";
  @SerializedName(SERIALIZED_NAME_STREET_NAME_RESULT)
  private String streetNameResult;

  public static final String SERIALIZED_NAME_STREET_NAME_ALIAS_TYPE = "StreetName.Alias.Type";
  @SerializedName(SERIALIZED_NAME_STREET_NAME_ALIAS_TYPE)
  private String streetNameAliasType;

  public static final String SERIALIZED_NAME_STREET_SUFFIX_RESULT = "StreetSuffix.Result";
  @SerializedName(SERIALIZED_NAME_STREET_SUFFIX_RESULT)
  private String streetSuffixResult;

  public static final String SERIALIZED_NAME_TRAILING_DIRECTIONAL_RESULT = "TrailingDirectional.Result";
  @SerializedName(SERIALIZED_NAME_TRAILING_DIRECTIONAL_RESULT)
  private String trailingDirectionalResult;

  public static final String SERIALIZED_NAME_APARTMENT_LABEL_RESULT = "ApartmentLabel.Result";
  @SerializedName(SERIALIZED_NAME_APARTMENT_LABEL_RESULT)
  private String apartmentLabelResult;

  public static final String SERIALIZED_NAME_APARTMENT_NUMBER_RESULT = "ApartmentNumber.Result";
  @SerializedName(SERIALIZED_NAME_APARTMENT_NUMBER_RESULT)
  private String apartmentNumberResult;

  public static final String SERIALIZED_NAME_APARTMENT_LABEL2_RESULT = "ApartmentLabel2.Result";
  @SerializedName(SERIALIZED_NAME_APARTMENT_LABEL2_RESULT)
  private String apartmentLabel2Result;

  public static final String SERIALIZED_NAME_APARTMENT_NUMBER2_RESULT = "ApartmentNumber2.Result";
  @SerializedName(SERIALIZED_NAME_APARTMENT_NUMBER2_RESULT)
  private String apartmentNumber2Result;

  public static final String SERIALIZED_NAME_RR_H_C_RESULT = "RRHC.Result";
  @SerializedName(SERIALIZED_NAME_RR_H_C_RESULT)
  private String rrHCResult;

  public static final String SERIALIZED_NAME_RR_H_C_TYPE = "RRHC.Type";
  @SerializedName(SERIALIZED_NAME_RR_H_C_TYPE)
  private String rrHCType;

  public static final String SERIALIZED_NAME_PO_BOX_RESULT = "POBox.Result";
  @SerializedName(SERIALIZED_NAME_PO_BOX_RESULT)
  private String poBoxResult;

  public static final String SERIALIZED_NAME_CITY_RESULT = "City.Result";
  @SerializedName(SERIALIZED_NAME_CITY_RESULT)
  private String cityResult;

  public static final String SERIALIZED_NAME_STATE_PROVINCE_RESULT = "StateProvince.Result";
  @SerializedName(SERIALIZED_NAME_STATE_PROVINCE_RESULT)
  private String stateProvinceResult;

  public static final String SERIALIZED_NAME_POSTAL_CODE_RESULT = "PostalCode.Result";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_RESULT)
  private String postalCodeResult;

  public static final String SERIALIZED_NAME_POSTAL_CODE_CITY_RESULT = "PostalCodeCity.Result";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_CITY_RESULT)
  private String postalCodeCityResult;

  public static final String SERIALIZED_NAME_ADDRESS_RECORD_RESULT = "AddressRecord.Result";
  @SerializedName(SERIALIZED_NAME_ADDRESS_RECORD_RESULT)
  private String addressRecordResult;

  public static final String SERIALIZED_NAME_POSTAL_CODE_SOURCE = "PostalCode.Source";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_SOURCE)
  private String postalCodeSource;

  public static final String SERIALIZED_NAME_POSTAL_CODE_TYPE = "PostalCode.Type";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE_TYPE)
  private String postalCodeType;

  public static final String SERIALIZED_NAME_COUNTRY_RESULT = "Country.Result";
  @SerializedName(SERIALIZED_NAME_COUNTRY_RESULT)
  private String countryResult;

  public static final String SERIALIZED_NAME_FIRM_NAME_RESULT = "FirmName.Result";
  @SerializedName(SERIALIZED_NAME_FIRM_NAME_RESULT)
  private String firmNameResult;

  public static final String SERIALIZED_NAME_STREET_NAME_PREFERRED_ALIAS_RESULT = "StreetNamePreferredAlias.Result";
  @SerializedName(SERIALIZED_NAME_STREET_NAME_PREFERRED_ALIAS_RESULT)
  private String streetNamePreferredAliasResult;

  public static final String SERIALIZED_NAME_STREET_NAME_ABBREVIATED_ALIAS_RESULT = "StreetNameAbbreviatedAlias.Result";
  @SerializedName(SERIALIZED_NAME_STREET_NAME_ABBREVIATED_ALIAS_RESULT)
  private String streetNameAbbreviatedAliasResult;

  public static final String SERIALIZED_NAME_ADDRESS_LINE5 = "AddressLine5";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LINE5)
  private String addressLine5;

  public static final String SERIALIZED_NAME_ADDRESS_QUALITY = "AddressQuality";
  @SerializedName(SERIALIZED_NAME_ADDRESS_QUALITY)
  private String addressQuality;

  public static final String SERIALIZED_NAME_DELIVERABILITY = "Deliverability";
  @SerializedName(SERIALIZED_NAME_DELIVERABILITY)
  private String deliverability;

  public static final String SERIALIZED_NAME_ADDRESS_TYPE = "AddressType";
  @SerializedName(SERIALIZED_NAME_ADDRESS_TYPE)
  private String addressType;

  public static final String SERIALIZED_NAME_LOCALITY = "Locality";
  @SerializedName(SERIALIZED_NAME_LOCALITY)
  private String locality;

  public static final String SERIALIZED_NAME_CHANGE_SCORE = "ChangeScore";
  @SerializedName(SERIALIZED_NAME_CHANGE_SCORE)
  private String changeScore;

  public static final String SERIALIZED_NAME_SUBURB = "Suburb";
  @SerializedName(SERIALIZED_NAME_SUBURB)
  private String suburb;

  public static final String SERIALIZED_NAME_BLOCK_ADDRESS = "BlockAddress";
  @SerializedName(SERIALIZED_NAME_BLOCK_ADDRESS)
  private String blockAddress;

  public static final String SERIALIZED_NAME_LATITUDE = "Latitude";
  @SerializedName(SERIALIZED_NAME_LATITUDE)
  private String latitude;

  public static final String SERIALIZED_NAME_LONGITUDE = "Longitude";
  @SerializedName(SERIALIZED_NAME_LONGITUDE)
  private String longitude;

  public ValidateMailingAddressPremiumOutput() { 
  }

  public ValidateMailingAddressPremiumOutput userFields(List<GetPostalCodesAPIOutputUserFields> userFields) {
    
    this.userFields = userFields;
    return this;
  }

  public ValidateMailingAddressPremiumOutput addUserFieldsItem(GetPostalCodesAPIOutputUserFields userFieldsItem) {
    if (this.userFields == null) {
      this.userFields = new ArrayList<GetPostalCodesAPIOutputUserFields>();
    }
    this.userFields.add(userFieldsItem);
    return this;
  }

   /**
   * These fields are returned, unmodified, in the user_fields section of the response.
   * @return userFields
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "These fields are returned, unmodified, in the user_fields section of the response.")

  public List<GetPostalCodesAPIOutputUserFields> getUserFields() {
    return userFields;
  }


  public void setUserFields(List<GetPostalCodesAPIOutputUserFields> userFields) {
    this.userFields = userFields;
  }


  public ValidateMailingAddressPremiumOutput status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Reports the success or failure of the match attempt.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reports the success or failure of the match attempt.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ValidateMailingAddressPremiumOutput statusCode(String statusCode) {
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * Reason for failure, if there is one.
   * @return statusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reason for failure, if there is one.")

  public String getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }


  public ValidateMailingAddressPremiumOutput statusDescription(String statusDescription) {
    
    this.statusDescription = statusDescription;
    return this;
  }

   /**
   * Description of the problem, if there is one.
   * @return statusDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the problem, if there is one.")

  public String getStatusDescription() {
    return statusDescription;
  }


  public void setStatusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
  }


  public ValidateMailingAddressPremiumOutput confidence(String confidence) {
    
    this.confidence = confidence;
    return this;
  }

   /**
   * The level of confidence assigned to the address being returned.
   * @return confidence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The level of confidence assigned to the address being returned.")

  public String getConfidence() {
    return confidence;
  }


  public void setConfidence(String confidence) {
    this.confidence = confidence;
  }


  public ValidateMailingAddressPremiumOutput recordType(String recordType) {
    
    this.recordType = recordType;
    return this;
  }

   /**
   * Type of address record.
   * @return recordType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of address record.")

  public String getRecordType() {
    return recordType;
  }


  public void setRecordType(String recordType) {
    this.recordType = recordType;
  }


  public ValidateMailingAddressPremiumOutput recordTypeDefault(String recordTypeDefault) {
    
    this.recordTypeDefault = recordTypeDefault;
    return this;
  }

   /**
   * Code indicating the default match.
   * @return recordTypeDefault
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Code indicating the default match.")

  public String getRecordTypeDefault() {
    return recordTypeDefault;
  }


  public void setRecordTypeDefault(String recordTypeDefault) {
    this.recordTypeDefault = recordTypeDefault;
  }


  public ValidateMailingAddressPremiumOutput multipleMatches(String multipleMatches) {
    
    this.multipleMatches = multipleMatches;
    return this;
  }

   /**
   * Indicates which address component had multiple matches.
   * @return multipleMatches
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates which address component had multiple matches.")

  public String getMultipleMatches() {
    return multipleMatches;
  }


  public void setMultipleMatches(String multipleMatches) {
    this.multipleMatches = multipleMatches;
  }


  public ValidateMailingAddressPremiumOutput couldNotValidate(String couldNotValidate) {
    
    this.couldNotValidate = couldNotValidate;
    return this;
  }

   /**
   * Mentions the address component that could not be validated, in case no match is found.
   * @return couldNotValidate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Mentions the address component that could not be validated, in case no match is found.")

  public String getCouldNotValidate() {
    return couldNotValidate;
  }


  public void setCouldNotValidate(String couldNotValidate) {
    this.couldNotValidate = couldNotValidate;
  }


  public ValidateMailingAddressPremiumOutput countryLevel(String countryLevel) {
    
    this.countryLevel = countryLevel;
    return this;
  }

   /**
   * The category of address matching available.
   * @return countryLevel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The category of address matching available.")

  public String getCountryLevel() {
    return countryLevel;
  }


  public void setCountryLevel(String countryLevel) {
    this.countryLevel = countryLevel;
  }


  public ValidateMailingAddressPremiumOutput addressFormat(String addressFormat) {
    
    this.addressFormat = addressFormat;
    return this;
  }

   /**
   * The type of address data being returned.
   * @return addressFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of address data being returned.")

  public String getAddressFormat() {
    return addressFormat;
  }


  public void setAddressFormat(String addressFormat) {
    this.addressFormat = addressFormat;
  }


  public ValidateMailingAddressPremiumOutput addressLine1(String addressLine1) {
    
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * The first line of the validated address.
   * @return addressLine1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The first line of the validated address.")

  public String getAddressLine1() {
    return addressLine1;
  }


  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }


  public ValidateMailingAddressPremiumOutput addressLine2(String addressLine2) {
    
    this.addressLine2 = addressLine2;
    return this;
  }

   /**
   * The second line of the validated address.
   * @return addressLine2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The second line of the validated address.")

  public String getAddressLine2() {
    return addressLine2;
  }


  public void setAddressLine2(String addressLine2) {
    this.addressLine2 = addressLine2;
  }


  public ValidateMailingAddressPremiumOutput addressLine3(String addressLine3) {
    
    this.addressLine3 = addressLine3;
    return this;
  }

   /**
   * The third line of the validated address.
   * @return addressLine3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The third line of the validated address.")

  public String getAddressLine3() {
    return addressLine3;
  }


  public void setAddressLine3(String addressLine3) {
    this.addressLine3 = addressLine3;
  }


  public ValidateMailingAddressPremiumOutput addressLine4(String addressLine4) {
    
    this.addressLine4 = addressLine4;
    return this;
  }

   /**
   * The fourth line of the validated address.
   * @return addressLine4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fourth line of the validated address.")

  public String getAddressLine4() {
    return addressLine4;
  }


  public void setAddressLine4(String addressLine4) {
    this.addressLine4 = addressLine4;
  }


  public ValidateMailingAddressPremiumOutput city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * The validated city name.
   * @return city
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated city name.")

  public String getCity() {
    return city;
  }


  public void setCity(String city) {
    this.city = city;
  }


  public ValidateMailingAddressPremiumOutput stateProvince(String stateProvince) {
    
    this.stateProvince = stateProvince;
    return this;
  }

   /**
   * The validated state or province abbreviation.
   * @return stateProvince
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated state or province abbreviation.")

  public String getStateProvince() {
    return stateProvince;
  }


  public void setStateProvince(String stateProvince) {
    this.stateProvince = stateProvince;
  }


  public ValidateMailingAddressPremiumOutput postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * The validated ZIP Code or postal code.
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated ZIP Code or postal code.")

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public ValidateMailingAddressPremiumOutput postalCodeBase(String postalCodeBase) {
    
    this.postalCodeBase = postalCodeBase;
    return this;
  }

   /**
   * The 5-digit ZIP Code.
   * @return postalCodeBase
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The 5-digit ZIP Code.")

  public String getPostalCodeBase() {
    return postalCodeBase;
  }


  public void setPostalCodeBase(String postalCodeBase) {
    this.postalCodeBase = postalCodeBase;
  }


  public ValidateMailingAddressPremiumOutput postalCodeAddOn(String postalCodeAddOn) {
    
    this.postalCodeAddOn = postalCodeAddOn;
    return this;
  }

   /**
   * The 4-digit add-on part of the ZIP Code.
   * @return postalCodeAddOn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The 4-digit add-on part of the ZIP Code.")

  public String getPostalCodeAddOn() {
    return postalCodeAddOn;
  }


  public void setPostalCodeAddOn(String postalCodeAddOn) {
    this.postalCodeAddOn = postalCodeAddOn;
  }


  public ValidateMailingAddressPremiumOutput country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * The country in the format determined by what you selected.
   * @return country
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The country in the format determined by what you selected.")

  public String getCountry() {
    return country;
  }


  public void setCountry(String country) {
    this.country = country;
  }


  public ValidateMailingAddressPremiumOutput additionalInputData(String additionalInputData) {
    
    this.additionalInputData = additionalInputData;
    return this;
  }

   /**
   * Input data that could not be matched to a particular address component.
   * @return additionalInputData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Input data that could not be matched to a particular address component.")

  public String getAdditionalInputData() {
    return additionalInputData;
  }


  public void setAdditionalInputData(String additionalInputData) {
    this.additionalInputData = additionalInputData;
  }


  public ValidateMailingAddressPremiumOutput firmName(String firmName) {
    
    this.firmName = firmName;
    return this;
  }

   /**
   * The validated firm or company name.
   * @return firmName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated firm or company name.")

  public String getFirmName() {
    return firmName;
  }


  public void setFirmName(String firmName) {
    this.firmName = firmName;
  }


  public ValidateMailingAddressPremiumOutput houseNumber(String houseNumber) {
    
    this.houseNumber = houseNumber;
    return this;
  }

   /**
   * House number.
   * @return houseNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "House number.")

  public String getHouseNumber() {
    return houseNumber;
  }


  public void setHouseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
  }


  public ValidateMailingAddressPremiumOutput leadingDirectional(String leadingDirectional) {
    
    this.leadingDirectional = leadingDirectional;
    return this;
  }

   /**
   * Leading directional.
   * @return leadingDirectional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Leading directional.")

  public String getLeadingDirectional() {
    return leadingDirectional;
  }


  public void setLeadingDirectional(String leadingDirectional) {
    this.leadingDirectional = leadingDirectional;
  }


  public ValidateMailingAddressPremiumOutput streetName(String streetName) {
    
    this.streetName = streetName;
    return this;
  }

   /**
   * Street name.
   * @return streetName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Street name.")

  public String getStreetName() {
    return streetName;
  }


  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }


  public ValidateMailingAddressPremiumOutput streetSuffix(String streetSuffix) {
    
    this.streetSuffix = streetSuffix;
    return this;
  }

   /**
   * Street suffix.
   * @return streetSuffix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Street suffix.")

  public String getStreetSuffix() {
    return streetSuffix;
  }


  public void setStreetSuffix(String streetSuffix) {
    this.streetSuffix = streetSuffix;
  }


  public ValidateMailingAddressPremiumOutput trailingDirectional(String trailingDirectional) {
    
    this.trailingDirectional = trailingDirectional;
    return this;
  }

   /**
   * Trailing directional.
   * @return trailingDirectional
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Trailing directional.")

  public String getTrailingDirectional() {
    return trailingDirectional;
  }


  public void setTrailingDirectional(String trailingDirectional) {
    this.trailingDirectional = trailingDirectional;
  }


  public ValidateMailingAddressPremiumOutput apartmentLabel(String apartmentLabel) {
    
    this.apartmentLabel = apartmentLabel;
    return this;
  }

   /**
   * Apartment designator (such as STE or APT).
   * @return apartmentLabel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Apartment designator (such as STE or APT).")

  public String getApartmentLabel() {
    return apartmentLabel;
  }


  public void setApartmentLabel(String apartmentLabel) {
    this.apartmentLabel = apartmentLabel;
  }


  public ValidateMailingAddressPremiumOutput apartmentNumber(String apartmentNumber) {
    
    this.apartmentNumber = apartmentNumber;
    return this;
  }

   /**
   * Apartment number.
   * @return apartmentNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Apartment number.")

  public String getApartmentNumber() {
    return apartmentNumber;
  }


  public void setApartmentNumber(String apartmentNumber) {
    this.apartmentNumber = apartmentNumber;
  }


  public ValidateMailingAddressPremiumOutput apartmentLabel2(String apartmentLabel2) {
    
    this.apartmentLabel2 = apartmentLabel2;
    return this;
  }

   /**
   * Secondary apartment designator.
   * @return apartmentLabel2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Secondary apartment designator.")

  public String getApartmentLabel2() {
    return apartmentLabel2;
  }


  public void setApartmentLabel2(String apartmentLabel2) {
    this.apartmentLabel2 = apartmentLabel2;
  }


  public ValidateMailingAddressPremiumOutput apartmentNumber2(String apartmentNumber2) {
    
    this.apartmentNumber2 = apartmentNumber2;
    return this;
  }

   /**
   * Secondary apartment number.
   * @return apartmentNumber2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Secondary apartment number.")

  public String getApartmentNumber2() {
    return apartmentNumber2;
  }


  public void setApartmentNumber2(String apartmentNumber2) {
    this.apartmentNumber2 = apartmentNumber2;
  }


  public ValidateMailingAddressPremiumOutput RRHC(String RRHC) {
    
    this.RRHC = RRHC;
    return this;
  }

   /**
   * Rural Route/Highway Contract indicator.
   * @return RRHC
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rural Route/Highway Contract indicator.")

  public String getRRHC() {
    return RRHC;
  }


  public void setRRHC(String RRHC) {
    this.RRHC = RRHC;
  }


  public ValidateMailingAddressPremiumOutput poBox(String poBox) {
    
    this.poBox = poBox;
    return this;
  }

   /**
   * Post office box number.
   * @return poBox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Post office box number.")

  public String getPoBox() {
    return poBox;
  }


  public void setPoBox(String poBox) {
    this.poBox = poBox;
  }


  public ValidateMailingAddressPremiumOutput privateMailbox(String privateMailbox) {
    
    this.privateMailbox = privateMailbox;
    return this;
  }

   /**
   * Private mailbox indicator.
   * @return privateMailbox
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Private mailbox indicator.")

  public String getPrivateMailbox() {
    return privateMailbox;
  }


  public void setPrivateMailbox(String privateMailbox) {
    this.privateMailbox = privateMailbox;
  }


  public ValidateMailingAddressPremiumOutput privateMailboxType(String privateMailboxType) {
    
    this.privateMailboxType = privateMailboxType;
    return this;
  }

   /**
   * The type of private mailbox.
   * @return privateMailboxType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of private mailbox.")

  public String getPrivateMailboxType() {
    return privateMailboxType;
  }


  public void setPrivateMailboxType(String privateMailboxType) {
    this.privateMailboxType = privateMailboxType;
  }


  public ValidateMailingAddressPremiumOutput houseNumberInput(String houseNumberInput) {
    
    this.houseNumberInput = houseNumberInput;
    return this;
  }

   /**
   * House number.
   * @return houseNumberInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "House number.")

  public String getHouseNumberInput() {
    return houseNumberInput;
  }


  public void setHouseNumberInput(String houseNumberInput) {
    this.houseNumberInput = houseNumberInput;
  }


  public ValidateMailingAddressPremiumOutput leadingDirectionalInput(String leadingDirectionalInput) {
    
    this.leadingDirectionalInput = leadingDirectionalInput;
    return this;
  }

   /**
   * Leading directional.
   * @return leadingDirectionalInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Leading directional.")

  public String getLeadingDirectionalInput() {
    return leadingDirectionalInput;
  }


  public void setLeadingDirectionalInput(String leadingDirectionalInput) {
    this.leadingDirectionalInput = leadingDirectionalInput;
  }


  public ValidateMailingAddressPremiumOutput streetNameInput(String streetNameInput) {
    
    this.streetNameInput = streetNameInput;
    return this;
  }

   /**
   * Street name.
   * @return streetNameInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Street name.")

  public String getStreetNameInput() {
    return streetNameInput;
  }


  public void setStreetNameInput(String streetNameInput) {
    this.streetNameInput = streetNameInput;
  }


  public ValidateMailingAddressPremiumOutput streetSuffixInput(String streetSuffixInput) {
    
    this.streetSuffixInput = streetSuffixInput;
    return this;
  }

   /**
   * Street suffix.
   * @return streetSuffixInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Street suffix.")

  public String getStreetSuffixInput() {
    return streetSuffixInput;
  }


  public void setStreetSuffixInput(String streetSuffixInput) {
    this.streetSuffixInput = streetSuffixInput;
  }


  public ValidateMailingAddressPremiumOutput trailingDirectionalInput(String trailingDirectionalInput) {
    
    this.trailingDirectionalInput = trailingDirectionalInput;
    return this;
  }

   /**
   * Trailing directional.
   * @return trailingDirectionalInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Trailing directional.")

  public String getTrailingDirectionalInput() {
    return trailingDirectionalInput;
  }


  public void setTrailingDirectionalInput(String trailingDirectionalInput) {
    this.trailingDirectionalInput = trailingDirectionalInput;
  }


  public ValidateMailingAddressPremiumOutput apartmentLabelInput(String apartmentLabelInput) {
    
    this.apartmentLabelInput = apartmentLabelInput;
    return this;
  }

   /**
   * Apartment designator (such as STE or APT).
   * @return apartmentLabelInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Apartment designator (such as STE or APT).")

  public String getApartmentLabelInput() {
    return apartmentLabelInput;
  }


  public void setApartmentLabelInput(String apartmentLabelInput) {
    this.apartmentLabelInput = apartmentLabelInput;
  }


  public ValidateMailingAddressPremiumOutput apartmentNumberInput(String apartmentNumberInput) {
    
    this.apartmentNumberInput = apartmentNumberInput;
    return this;
  }

   /**
   * Apartment number.
   * @return apartmentNumberInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Apartment number.")

  public String getApartmentNumberInput() {
    return apartmentNumberInput;
  }


  public void setApartmentNumberInput(String apartmentNumberInput) {
    this.apartmentNumberInput = apartmentNumberInput;
  }


  public ValidateMailingAddressPremiumOutput rrHCInput(String rrHCInput) {
    
    this.rrHCInput = rrHCInput;
    return this;
  }

   /**
   * Rural Route/Highway Contract indicator.
   * @return rrHCInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rural Route/Highway Contract indicator.")

  public String getRrHCInput() {
    return rrHCInput;
  }


  public void setRrHCInput(String rrHCInput) {
    this.rrHCInput = rrHCInput;
  }


  public ValidateMailingAddressPremiumOutput poBoxInput(String poBoxInput) {
    
    this.poBoxInput = poBoxInput;
    return this;
  }

   /**
   * Post office box number.
   * @return poBoxInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Post office box number.")

  public String getPoBoxInput() {
    return poBoxInput;
  }


  public void setPoBoxInput(String poBoxInput) {
    this.poBoxInput = poBoxInput;
  }


  public ValidateMailingAddressPremiumOutput privateMailboxInput(String privateMailboxInput) {
    
    this.privateMailboxInput = privateMailboxInput;
    return this;
  }

   /**
   * Private mailbox indicator.
   * @return privateMailboxInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Private mailbox indicator.")

  public String getPrivateMailboxInput() {
    return privateMailboxInput;
  }


  public void setPrivateMailboxInput(String privateMailboxInput) {
    this.privateMailboxInput = privateMailboxInput;
  }


  public ValidateMailingAddressPremiumOutput privateMailboxTypeInput(String privateMailboxTypeInput) {
    
    this.privateMailboxTypeInput = privateMailboxTypeInput;
    return this;
  }

   /**
   * The type of private mailbox.
   * @return privateMailboxTypeInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of private mailbox.")

  public String getPrivateMailboxTypeInput() {
    return privateMailboxTypeInput;
  }


  public void setPrivateMailboxTypeInput(String privateMailboxTypeInput) {
    this.privateMailboxTypeInput = privateMailboxTypeInput;
  }


  public ValidateMailingAddressPremiumOutput cityInput(String cityInput) {
    
    this.cityInput = cityInput;
    return this;
  }

   /**
   * Validated city name.
   * @return cityInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Validated city name.")

  public String getCityInput() {
    return cityInput;
  }


  public void setCityInput(String cityInput) {
    this.cityInput = cityInput;
  }


  public ValidateMailingAddressPremiumOutput stateProvinceInput(String stateProvinceInput) {
    
    this.stateProvinceInput = stateProvinceInput;
    return this;
  }

   /**
   * Validated state or province name.
   * @return stateProvinceInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Validated state or province name.")

  public String getStateProvinceInput() {
    return stateProvinceInput;
  }


  public void setStateProvinceInput(String stateProvinceInput) {
    this.stateProvinceInput = stateProvinceInput;
  }


  public ValidateMailingAddressPremiumOutput postalCodeInput(String postalCodeInput) {
    
    this.postalCodeInput = postalCodeInput;
    return this;
  }

   /**
   * Validated postal code.
   * @return postalCodeInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Validated postal code.")

  public String getPostalCodeInput() {
    return postalCodeInput;
  }


  public void setPostalCodeInput(String postalCodeInput) {
    this.postalCodeInput = postalCodeInput;
  }


  public ValidateMailingAddressPremiumOutput countryInput(String countryInput) {
    
    this.countryInput = countryInput;
    return this;
  }

   /**
   * Country. Format is determined by what you selected in OutputCountryFormat.
   * @return countryInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Country. Format is determined by what you selected in OutputCountryFormat.")

  public String getCountryInput() {
    return countryInput;
  }


  public void setCountryInput(String countryInput) {
    this.countryInput = countryInput;
  }


  public ValidateMailingAddressPremiumOutput firmNameInput(String firmNameInput) {
    
    this.firmNameInput = firmNameInput;
    return this;
  }

   /**
   * The validated firm or company name.
   * @return firmNameInput
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated firm or company name.")

  public String getFirmNameInput() {
    return firmNameInput;
  }


  public void setFirmNameInput(String firmNameInput) {
    this.firmNameInput = firmNameInput;
  }


  public ValidateMailingAddressPremiumOutput houseNumberResult(String houseNumberResult) {
    
    this.houseNumberResult = houseNumberResult;
    return this;
  }

   /**
   * The field-level result indicator for HouseNumber.
   * @return houseNumberResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for HouseNumber.")

  public String getHouseNumberResult() {
    return houseNumberResult;
  }


  public void setHouseNumberResult(String houseNumberResult) {
    this.houseNumberResult = houseNumberResult;
  }


  public ValidateMailingAddressPremiumOutput leadingDirectionalResult(String leadingDirectionalResult) {
    
    this.leadingDirectionalResult = leadingDirectionalResult;
    return this;
  }

   /**
   * The field-level result indicator for LeadingDirectional.
   * @return leadingDirectionalResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for LeadingDirectional.")

  public String getLeadingDirectionalResult() {
    return leadingDirectionalResult;
  }


  public void setLeadingDirectionalResult(String leadingDirectionalResult) {
    this.leadingDirectionalResult = leadingDirectionalResult;
  }


  public ValidateMailingAddressPremiumOutput streetResult(String streetResult) {
    
    this.streetResult = streetResult;
    return this;
  }

   /**
   * The field-level result indicator for Street.
   * @return streetResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for Street.")

  public String getStreetResult() {
    return streetResult;
  }


  public void setStreetResult(String streetResult) {
    this.streetResult = streetResult;
  }


  public ValidateMailingAddressPremiumOutput streetNameResult(String streetNameResult) {
    
    this.streetNameResult = streetNameResult;
    return this;
  }

   /**
   * The field-level result indicator for StreetName.
   * @return streetNameResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for StreetName.")

  public String getStreetNameResult() {
    return streetNameResult;
  }


  public void setStreetNameResult(String streetNameResult) {
    this.streetNameResult = streetNameResult;
  }


  public ValidateMailingAddressPremiumOutput streetNameAliasType(String streetNameAliasType) {
    
    this.streetNameAliasType = streetNameAliasType;
    return this;
  }

   /**
   * The field-level result indicator for StreetName Alias.
   * @return streetNameAliasType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for StreetName Alias.")

  public String getStreetNameAliasType() {
    return streetNameAliasType;
  }


  public void setStreetNameAliasType(String streetNameAliasType) {
    this.streetNameAliasType = streetNameAliasType;
  }


  public ValidateMailingAddressPremiumOutput streetSuffixResult(String streetSuffixResult) {
    
    this.streetSuffixResult = streetSuffixResult;
    return this;
  }

   /**
   * The field-level result indicator for StreetSuffix.
   * @return streetSuffixResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for StreetSuffix.")

  public String getStreetSuffixResult() {
    return streetSuffixResult;
  }


  public void setStreetSuffixResult(String streetSuffixResult) {
    this.streetSuffixResult = streetSuffixResult;
  }


  public ValidateMailingAddressPremiumOutput trailingDirectionalResult(String trailingDirectionalResult) {
    
    this.trailingDirectionalResult = trailingDirectionalResult;
    return this;
  }

   /**
   * The field-level result indicator for TrailingDirectional.
   * @return trailingDirectionalResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for TrailingDirectional.")

  public String getTrailingDirectionalResult() {
    return trailingDirectionalResult;
  }


  public void setTrailingDirectionalResult(String trailingDirectionalResult) {
    this.trailingDirectionalResult = trailingDirectionalResult;
  }


  public ValidateMailingAddressPremiumOutput apartmentLabelResult(String apartmentLabelResult) {
    
    this.apartmentLabelResult = apartmentLabelResult;
    return this;
  }

   /**
   * The field-level result indicator for ApartmentLabel.
   * @return apartmentLabelResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for ApartmentLabel.")

  public String getApartmentLabelResult() {
    return apartmentLabelResult;
  }


  public void setApartmentLabelResult(String apartmentLabelResult) {
    this.apartmentLabelResult = apartmentLabelResult;
  }


  public ValidateMailingAddressPremiumOutput apartmentNumberResult(String apartmentNumberResult) {
    
    this.apartmentNumberResult = apartmentNumberResult;
    return this;
  }

   /**
   * The field-level result indicator for ApartmentNumber.
   * @return apartmentNumberResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for ApartmentNumber.")

  public String getApartmentNumberResult() {
    return apartmentNumberResult;
  }


  public void setApartmentNumberResult(String apartmentNumberResult) {
    this.apartmentNumberResult = apartmentNumberResult;
  }


  public ValidateMailingAddressPremiumOutput apartmentLabel2Result(String apartmentLabel2Result) {
    
    this.apartmentLabel2Result = apartmentLabel2Result;
    return this;
  }

   /**
   * The field-level result indicator for ApartmentLabel2.
   * @return apartmentLabel2Result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for ApartmentLabel2.")

  public String getApartmentLabel2Result() {
    return apartmentLabel2Result;
  }


  public void setApartmentLabel2Result(String apartmentLabel2Result) {
    this.apartmentLabel2Result = apartmentLabel2Result;
  }


  public ValidateMailingAddressPremiumOutput apartmentNumber2Result(String apartmentNumber2Result) {
    
    this.apartmentNumber2Result = apartmentNumber2Result;
    return this;
  }

   /**
   * The field-level result indicator for ApartmentNumber2.
   * @return apartmentNumber2Result
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for ApartmentNumber2.")

  public String getApartmentNumber2Result() {
    return apartmentNumber2Result;
  }


  public void setApartmentNumber2Result(String apartmentNumber2Result) {
    this.apartmentNumber2Result = apartmentNumber2Result;
  }


  public ValidateMailingAddressPremiumOutput rrHCResult(String rrHCResult) {
    
    this.rrHCResult = rrHCResult;
    return this;
  }

   /**
   * The field-level result indicator for RRHC.
   * @return rrHCResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for RRHC.")

  public String getRrHCResult() {
    return rrHCResult;
  }


  public void setRrHCResult(String rrHCResult) {
    this.rrHCResult = rrHCResult;
  }


  public ValidateMailingAddressPremiumOutput rrHCType(String rrHCType) {
    
    this.rrHCType = rrHCType;
    return this;
  }

   /**
   * The field-level result indicator for RRHC Type.
   * @return rrHCType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for RRHC Type.")

  public String getRrHCType() {
    return rrHCType;
  }


  public void setRrHCType(String rrHCType) {
    this.rrHCType = rrHCType;
  }


  public ValidateMailingAddressPremiumOutput poBoxResult(String poBoxResult) {
    
    this.poBoxResult = poBoxResult;
    return this;
  }

   /**
   * The field-level result indicator for POBox.
   * @return poBoxResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for POBox.")

  public String getPoBoxResult() {
    return poBoxResult;
  }


  public void setPoBoxResult(String poBoxResult) {
    this.poBoxResult = poBoxResult;
  }


  public ValidateMailingAddressPremiumOutput cityResult(String cityResult) {
    
    this.cityResult = cityResult;
    return this;
  }

   /**
   * The field-level result indicator for City.
   * @return cityResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for City.")

  public String getCityResult() {
    return cityResult;
  }


  public void setCityResult(String cityResult) {
    this.cityResult = cityResult;
  }


  public ValidateMailingAddressPremiumOutput stateProvinceResult(String stateProvinceResult) {
    
    this.stateProvinceResult = stateProvinceResult;
    return this;
  }

   /**
   * The field-level result indicator for StateProvince.
   * @return stateProvinceResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for StateProvince.")

  public String getStateProvinceResult() {
    return stateProvinceResult;
  }


  public void setStateProvinceResult(String stateProvinceResult) {
    this.stateProvinceResult = stateProvinceResult;
  }


  public ValidateMailingAddressPremiumOutput postalCodeResult(String postalCodeResult) {
    
    this.postalCodeResult = postalCodeResult;
    return this;
  }

   /**
   * The field-level result indicator for PostalCode.
   * @return postalCodeResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for PostalCode.")

  public String getPostalCodeResult() {
    return postalCodeResult;
  }


  public void setPostalCodeResult(String postalCodeResult) {
    this.postalCodeResult = postalCodeResult;
  }


  public ValidateMailingAddressPremiumOutput postalCodeCityResult(String postalCodeCityResult) {
    
    this.postalCodeCityResult = postalCodeCityResult;
    return this;
  }

   /**
   * The field-level result indicator for PostalCodeCity.
   * @return postalCodeCityResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for PostalCodeCity.")

  public String getPostalCodeCityResult() {
    return postalCodeCityResult;
  }


  public void setPostalCodeCityResult(String postalCodeCityResult) {
    this.postalCodeCityResult = postalCodeCityResult;
  }


  public ValidateMailingAddressPremiumOutput addressRecordResult(String addressRecordResult) {
    
    this.addressRecordResult = addressRecordResult;
    return this;
  }

   /**
   * The field-level result indicator for AddressRecord.
   * @return addressRecordResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for AddressRecord.")

  public String getAddressRecordResult() {
    return addressRecordResult;
  }


  public void setAddressRecordResult(String addressRecordResult) {
    this.addressRecordResult = addressRecordResult;
  }


  public ValidateMailingAddressPremiumOutput postalCodeSource(String postalCodeSource) {
    
    this.postalCodeSource = postalCodeSource;
    return this;
  }

   /**
   * The field-level result indicator for PostalCode Source.
   * @return postalCodeSource
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The field-level result indicator for PostalCode Source.")

  public String getPostalCodeSource() {
    return postalCodeSource;
  }


  public void setPostalCodeSource(String postalCodeSource) {
    this.postalCodeSource = postalCodeSource;
  }


  public ValidateMailingAddressPremiumOutput postalCodeType(String postalCodeType) {
    
    this.postalCodeType = postalCodeType;
    return this;
  }

   /**
   * Indicates the type of postal code returned.
   * @return postalCodeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the type of postal code returned.")

  public String getPostalCodeType() {
    return postalCodeType;
  }


  public void setPostalCodeType(String postalCodeType) {
    this.postalCodeType = postalCodeType;
  }


  public ValidateMailingAddressPremiumOutput countryResult(String countryResult) {
    
    this.countryResult = countryResult;
    return this;
  }

   /**
   * The validated firm or company name.
   * @return countryResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated firm or company name.")

  public String getCountryResult() {
    return countryResult;
  }


  public void setCountryResult(String countryResult) {
    this.countryResult = countryResult;
  }


  public ValidateMailingAddressPremiumOutput firmNameResult(String firmNameResult) {
    
    this.firmNameResult = firmNameResult;
    return this;
  }

   /**
   * Indicates if the firm name got validated.
   * @return firmNameResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates if the firm name got validated.")

  public String getFirmNameResult() {
    return firmNameResult;
  }


  public void setFirmNameResult(String firmNameResult) {
    this.firmNameResult = firmNameResult;
  }


  public ValidateMailingAddressPremiumOutput streetNamePreferredAliasResult(String streetNamePreferredAliasResult) {
    
    this.streetNamePreferredAliasResult = streetNamePreferredAliasResult;
    return this;
  }

   /**
   * Indicates the result of preferred alias processing.
   * @return streetNamePreferredAliasResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the result of preferred alias processing.")

  public String getStreetNamePreferredAliasResult() {
    return streetNamePreferredAliasResult;
  }


  public void setStreetNamePreferredAliasResult(String streetNamePreferredAliasResult) {
    this.streetNamePreferredAliasResult = streetNamePreferredAliasResult;
  }


  public ValidateMailingAddressPremiumOutput streetNameAbbreviatedAliasResult(String streetNameAbbreviatedAliasResult) {
    
    this.streetNameAbbreviatedAliasResult = streetNameAbbreviatedAliasResult;
    return this;
  }

   /**
   * Indicates the result of abbreviated alias processing.
   * @return streetNameAbbreviatedAliasResult
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the result of abbreviated alias processing.")

  public String getStreetNameAbbreviatedAliasResult() {
    return streetNameAbbreviatedAliasResult;
  }


  public void setStreetNameAbbreviatedAliasResult(String streetNameAbbreviatedAliasResult) {
    this.streetNameAbbreviatedAliasResult = streetNameAbbreviatedAliasResult;
  }


  public ValidateMailingAddressPremiumOutput addressLine5(String addressLine5) {
    
    this.addressLine5 = addressLine5;
    return this;
  }

   /**
   * The fifth line of the validated address.
   * @return addressLine5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The fifth line of the validated address.")

  public String getAddressLine5() {
    return addressLine5;
  }


  public void setAddressLine5(String addressLine5) {
    this.addressLine5 = addressLine5;
  }


  public ValidateMailingAddressPremiumOutput addressQuality(String addressQuality) {
    
    this.addressQuality = addressQuality;
    return this;
  }

   /**
   * A two character code indicating overall quality of the resulting address.
   * @return addressQuality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A two character code indicating overall quality of the resulting address.")

  public String getAddressQuality() {
    return addressQuality;
  }


  public void setAddressQuality(String addressQuality) {
    this.addressQuality = addressQuality;
  }


  public ValidateMailingAddressPremiumOutput deliverability(String deliverability) {
    
    this.deliverability = deliverability;
    return this;
  }

   /**
   * An estimate of confidence that an item mailed or shipped to this address would be successfully delivered.
   * @return deliverability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An estimate of confidence that an item mailed or shipped to this address would be successfully delivered.")

  public String getDeliverability() {
    return deliverability;
  }


  public void setDeliverability(String deliverability) {
    this.deliverability = deliverability;
  }


  public ValidateMailingAddressPremiumOutput addressType(String addressType) {
    
    this.addressType = addressType;
    return this;
  }

   /**
   * A single letter code that indicates the type of address.
   * @return addressType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A single letter code that indicates the type of address.")

  public String getAddressType() {
    return addressType;
  }


  public void setAddressType(String addressType) {
    this.addressType = addressType;
  }


  public ValidateMailingAddressPremiumOutput locality(String locality) {
    
    this.locality = locality;
    return this;
  }

   /**
   * A locality is a village in rural areas or it may be a suburb in urban areas.
   * @return locality
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A locality is a village in rural areas or it may be a suburb in urban areas.")

  public String getLocality() {
    return locality;
  }


  public void setLocality(String locality) {
    this.locality = locality;
  }


  public ValidateMailingAddressPremiumOutput changeScore(String changeScore) {
    
    this.changeScore = changeScore;
    return this;
  }

   /**
   * A value of 0 and 100 that reflects how much the address has changed to make it valid.
   * @return changeScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A value of 0 and 100 that reflects how much the address has changed to make it valid.")

  public String getChangeScore() {
    return changeScore;
  }


  public void setChangeScore(String changeScore) {
    this.changeScore = changeScore;
  }


  public ValidateMailingAddressPremiumOutput suburb(String suburb) {
    
    this.suburb = suburb;
    return this;
  }

   /**
   * The validated firm or company name.
   * @return suburb
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The validated firm or company name.")

  public String getSuburb() {
    return suburb;
  }


  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }


  public ValidateMailingAddressPremiumOutput blockAddress(String blockAddress) {
    
    this.blockAddress = blockAddress;
    return this;
  }

   /**
   * It is the formatted address, as it would appear on a physical mail piece.
   * @return blockAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "It is the formatted address, as it would appear on a physical mail piece.")

  public String getBlockAddress() {
    return blockAddress;
  }


  public void setBlockAddress(String blockAddress) {
    this.blockAddress = blockAddress;
  }


  public ValidateMailingAddressPremiumOutput latitude(String latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Seven-digit number in degrees, calculated to four decimal places.
   * @return latitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Seven-digit number in degrees, calculated to four decimal places.")

  public String getLatitude() {
    return latitude;
  }


  public void setLatitude(String latitude) {
    this.latitude = latitude;
  }


  public ValidateMailingAddressPremiumOutput longitude(String longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Seven-digit number in degrees, calculated to four decimal places.
   * @return longitude
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Seven-digit number in degrees, calculated to four decimal places.")

  public String getLongitude() {
    return longitude;
  }


  public void setLongitude(String longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidateMailingAddressPremiumOutput validateMailingAddressPremiumOutput = (ValidateMailingAddressPremiumOutput) o;
    return Objects.equals(this.userFields, validateMailingAddressPremiumOutput.userFields) &&
        Objects.equals(this.status, validateMailingAddressPremiumOutput.status) &&
        Objects.equals(this.statusCode, validateMailingAddressPremiumOutput.statusCode) &&
        Objects.equals(this.statusDescription, validateMailingAddressPremiumOutput.statusDescription) &&
        Objects.equals(this.confidence, validateMailingAddressPremiumOutput.confidence) &&
        Objects.equals(this.recordType, validateMailingAddressPremiumOutput.recordType) &&
        Objects.equals(this.recordTypeDefault, validateMailingAddressPremiumOutput.recordTypeDefault) &&
        Objects.equals(this.multipleMatches, validateMailingAddressPremiumOutput.multipleMatches) &&
        Objects.equals(this.couldNotValidate, validateMailingAddressPremiumOutput.couldNotValidate) &&
        Objects.equals(this.countryLevel, validateMailingAddressPremiumOutput.countryLevel) &&
        Objects.equals(this.addressFormat, validateMailingAddressPremiumOutput.addressFormat) &&
        Objects.equals(this.addressLine1, validateMailingAddressPremiumOutput.addressLine1) &&
        Objects.equals(this.addressLine2, validateMailingAddressPremiumOutput.addressLine2) &&
        Objects.equals(this.addressLine3, validateMailingAddressPremiumOutput.addressLine3) &&
        Objects.equals(this.addressLine4, validateMailingAddressPremiumOutput.addressLine4) &&
        Objects.equals(this.city, validateMailingAddressPremiumOutput.city) &&
        Objects.equals(this.stateProvince, validateMailingAddressPremiumOutput.stateProvince) &&
        Objects.equals(this.postalCode, validateMailingAddressPremiumOutput.postalCode) &&
        Objects.equals(this.postalCodeBase, validateMailingAddressPremiumOutput.postalCodeBase) &&
        Objects.equals(this.postalCodeAddOn, validateMailingAddressPremiumOutput.postalCodeAddOn) &&
        Objects.equals(this.country, validateMailingAddressPremiumOutput.country) &&
        Objects.equals(this.additionalInputData, validateMailingAddressPremiumOutput.additionalInputData) &&
        Objects.equals(this.firmName, validateMailingAddressPremiumOutput.firmName) &&
        Objects.equals(this.houseNumber, validateMailingAddressPremiumOutput.houseNumber) &&
        Objects.equals(this.leadingDirectional, validateMailingAddressPremiumOutput.leadingDirectional) &&
        Objects.equals(this.streetName, validateMailingAddressPremiumOutput.streetName) &&
        Objects.equals(this.streetSuffix, validateMailingAddressPremiumOutput.streetSuffix) &&
        Objects.equals(this.trailingDirectional, validateMailingAddressPremiumOutput.trailingDirectional) &&
        Objects.equals(this.apartmentLabel, validateMailingAddressPremiumOutput.apartmentLabel) &&
        Objects.equals(this.apartmentNumber, validateMailingAddressPremiumOutput.apartmentNumber) &&
        Objects.equals(this.apartmentLabel2, validateMailingAddressPremiumOutput.apartmentLabel2) &&
        Objects.equals(this.apartmentNumber2, validateMailingAddressPremiumOutput.apartmentNumber2) &&
        Objects.equals(this.RRHC, validateMailingAddressPremiumOutput.RRHC) &&
        Objects.equals(this.poBox, validateMailingAddressPremiumOutput.poBox) &&
        Objects.equals(this.privateMailbox, validateMailingAddressPremiumOutput.privateMailbox) &&
        Objects.equals(this.privateMailboxType, validateMailingAddressPremiumOutput.privateMailboxType) &&
        Objects.equals(this.houseNumberInput, validateMailingAddressPremiumOutput.houseNumberInput) &&
        Objects.equals(this.leadingDirectionalInput, validateMailingAddressPremiumOutput.leadingDirectionalInput) &&
        Objects.equals(this.streetNameInput, validateMailingAddressPremiumOutput.streetNameInput) &&
        Objects.equals(this.streetSuffixInput, validateMailingAddressPremiumOutput.streetSuffixInput) &&
        Objects.equals(this.trailingDirectionalInput, validateMailingAddressPremiumOutput.trailingDirectionalInput) &&
        Objects.equals(this.apartmentLabelInput, validateMailingAddressPremiumOutput.apartmentLabelInput) &&
        Objects.equals(this.apartmentNumberInput, validateMailingAddressPremiumOutput.apartmentNumberInput) &&
        Objects.equals(this.rrHCInput, validateMailingAddressPremiumOutput.rrHCInput) &&
        Objects.equals(this.poBoxInput, validateMailingAddressPremiumOutput.poBoxInput) &&
        Objects.equals(this.privateMailboxInput, validateMailingAddressPremiumOutput.privateMailboxInput) &&
        Objects.equals(this.privateMailboxTypeInput, validateMailingAddressPremiumOutput.privateMailboxTypeInput) &&
        Objects.equals(this.cityInput, validateMailingAddressPremiumOutput.cityInput) &&
        Objects.equals(this.stateProvinceInput, validateMailingAddressPremiumOutput.stateProvinceInput) &&
        Objects.equals(this.postalCodeInput, validateMailingAddressPremiumOutput.postalCodeInput) &&
        Objects.equals(this.countryInput, validateMailingAddressPremiumOutput.countryInput) &&
        Objects.equals(this.firmNameInput, validateMailingAddressPremiumOutput.firmNameInput) &&
        Objects.equals(this.houseNumberResult, validateMailingAddressPremiumOutput.houseNumberResult) &&
        Objects.equals(this.leadingDirectionalResult, validateMailingAddressPremiumOutput.leadingDirectionalResult) &&
        Objects.equals(this.streetResult, validateMailingAddressPremiumOutput.streetResult) &&
        Objects.equals(this.streetNameResult, validateMailingAddressPremiumOutput.streetNameResult) &&
        Objects.equals(this.streetNameAliasType, validateMailingAddressPremiumOutput.streetNameAliasType) &&
        Objects.equals(this.streetSuffixResult, validateMailingAddressPremiumOutput.streetSuffixResult) &&
        Objects.equals(this.trailingDirectionalResult, validateMailingAddressPremiumOutput.trailingDirectionalResult) &&
        Objects.equals(this.apartmentLabelResult, validateMailingAddressPremiumOutput.apartmentLabelResult) &&
        Objects.equals(this.apartmentNumberResult, validateMailingAddressPremiumOutput.apartmentNumberResult) &&
        Objects.equals(this.apartmentLabel2Result, validateMailingAddressPremiumOutput.apartmentLabel2Result) &&
        Objects.equals(this.apartmentNumber2Result, validateMailingAddressPremiumOutput.apartmentNumber2Result) &&
        Objects.equals(this.rrHCResult, validateMailingAddressPremiumOutput.rrHCResult) &&
        Objects.equals(this.rrHCType, validateMailingAddressPremiumOutput.rrHCType) &&
        Objects.equals(this.poBoxResult, validateMailingAddressPremiumOutput.poBoxResult) &&
        Objects.equals(this.cityResult, validateMailingAddressPremiumOutput.cityResult) &&
        Objects.equals(this.stateProvinceResult, validateMailingAddressPremiumOutput.stateProvinceResult) &&
        Objects.equals(this.postalCodeResult, validateMailingAddressPremiumOutput.postalCodeResult) &&
        Objects.equals(this.postalCodeCityResult, validateMailingAddressPremiumOutput.postalCodeCityResult) &&
        Objects.equals(this.addressRecordResult, validateMailingAddressPremiumOutput.addressRecordResult) &&
        Objects.equals(this.postalCodeSource, validateMailingAddressPremiumOutput.postalCodeSource) &&
        Objects.equals(this.postalCodeType, validateMailingAddressPremiumOutput.postalCodeType) &&
        Objects.equals(this.countryResult, validateMailingAddressPremiumOutput.countryResult) &&
        Objects.equals(this.firmNameResult, validateMailingAddressPremiumOutput.firmNameResult) &&
        Objects.equals(this.streetNamePreferredAliasResult, validateMailingAddressPremiumOutput.streetNamePreferredAliasResult) &&
        Objects.equals(this.streetNameAbbreviatedAliasResult, validateMailingAddressPremiumOutput.streetNameAbbreviatedAliasResult) &&
        Objects.equals(this.addressLine5, validateMailingAddressPremiumOutput.addressLine5) &&
        Objects.equals(this.addressQuality, validateMailingAddressPremiumOutput.addressQuality) &&
        Objects.equals(this.deliverability, validateMailingAddressPremiumOutput.deliverability) &&
        Objects.equals(this.addressType, validateMailingAddressPremiumOutput.addressType) &&
        Objects.equals(this.locality, validateMailingAddressPremiumOutput.locality) &&
        Objects.equals(this.changeScore, validateMailingAddressPremiumOutput.changeScore) &&
        Objects.equals(this.suburb, validateMailingAddressPremiumOutput.suburb) &&
        Objects.equals(this.blockAddress, validateMailingAddressPremiumOutput.blockAddress) &&
        Objects.equals(this.latitude, validateMailingAddressPremiumOutput.latitude) &&
        Objects.equals(this.longitude, validateMailingAddressPremiumOutput.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userFields, status, statusCode, statusDescription, confidence, recordType, recordTypeDefault, multipleMatches, couldNotValidate, countryLevel, addressFormat, addressLine1, addressLine2, addressLine3, addressLine4, city, stateProvince, postalCode, postalCodeBase, postalCodeAddOn, country, additionalInputData, firmName, houseNumber, leadingDirectional, streetName, streetSuffix, trailingDirectional, apartmentLabel, apartmentNumber, apartmentLabel2, apartmentNumber2, RRHC, poBox, privateMailbox, privateMailboxType, houseNumberInput, leadingDirectionalInput, streetNameInput, streetSuffixInput, trailingDirectionalInput, apartmentLabelInput, apartmentNumberInput, rrHCInput, poBoxInput, privateMailboxInput, privateMailboxTypeInput, cityInput, stateProvinceInput, postalCodeInput, countryInput, firmNameInput, houseNumberResult, leadingDirectionalResult, streetResult, streetNameResult, streetNameAliasType, streetSuffixResult, trailingDirectionalResult, apartmentLabelResult, apartmentNumberResult, apartmentLabel2Result, apartmentNumber2Result, rrHCResult, rrHCType, poBoxResult, cityResult, stateProvinceResult, postalCodeResult, postalCodeCityResult, addressRecordResult, postalCodeSource, postalCodeType, countryResult, firmNameResult, streetNamePreferredAliasResult, streetNameAbbreviatedAliasResult, addressLine5, addressQuality, deliverability, addressType, locality, changeScore, suburb, blockAddress, latitude, longitude);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidateMailingAddressPremiumOutput {\n");
    sb.append("    userFields: ").append(toIndentedString(userFields)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    recordType: ").append(toIndentedString(recordType)).append("\n");
    sb.append("    recordTypeDefault: ").append(toIndentedString(recordTypeDefault)).append("\n");
    sb.append("    multipleMatches: ").append(toIndentedString(multipleMatches)).append("\n");
    sb.append("    couldNotValidate: ").append(toIndentedString(couldNotValidate)).append("\n");
    sb.append("    countryLevel: ").append(toIndentedString(countryLevel)).append("\n");
    sb.append("    addressFormat: ").append(toIndentedString(addressFormat)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    addressLine2: ").append(toIndentedString(addressLine2)).append("\n");
    sb.append("    addressLine3: ").append(toIndentedString(addressLine3)).append("\n");
    sb.append("    addressLine4: ").append(toIndentedString(addressLine4)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    stateProvince: ").append(toIndentedString(stateProvince)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    postalCodeBase: ").append(toIndentedString(postalCodeBase)).append("\n");
    sb.append("    postalCodeAddOn: ").append(toIndentedString(postalCodeAddOn)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    additionalInputData: ").append(toIndentedString(additionalInputData)).append("\n");
    sb.append("    firmName: ").append(toIndentedString(firmName)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    leadingDirectional: ").append(toIndentedString(leadingDirectional)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    streetSuffix: ").append(toIndentedString(streetSuffix)).append("\n");
    sb.append("    trailingDirectional: ").append(toIndentedString(trailingDirectional)).append("\n");
    sb.append("    apartmentLabel: ").append(toIndentedString(apartmentLabel)).append("\n");
    sb.append("    apartmentNumber: ").append(toIndentedString(apartmentNumber)).append("\n");
    sb.append("    apartmentLabel2: ").append(toIndentedString(apartmentLabel2)).append("\n");
    sb.append("    apartmentNumber2: ").append(toIndentedString(apartmentNumber2)).append("\n");
    sb.append("    RRHC: ").append(toIndentedString(RRHC)).append("\n");
    sb.append("    poBox: ").append(toIndentedString(poBox)).append("\n");
    sb.append("    privateMailbox: ").append(toIndentedString(privateMailbox)).append("\n");
    sb.append("    privateMailboxType: ").append(toIndentedString(privateMailboxType)).append("\n");
    sb.append("    houseNumberInput: ").append(toIndentedString(houseNumberInput)).append("\n");
    sb.append("    leadingDirectionalInput: ").append(toIndentedString(leadingDirectionalInput)).append("\n");
    sb.append("    streetNameInput: ").append(toIndentedString(streetNameInput)).append("\n");
    sb.append("    streetSuffixInput: ").append(toIndentedString(streetSuffixInput)).append("\n");
    sb.append("    trailingDirectionalInput: ").append(toIndentedString(trailingDirectionalInput)).append("\n");
    sb.append("    apartmentLabelInput: ").append(toIndentedString(apartmentLabelInput)).append("\n");
    sb.append("    apartmentNumberInput: ").append(toIndentedString(apartmentNumberInput)).append("\n");
    sb.append("    rrHCInput: ").append(toIndentedString(rrHCInput)).append("\n");
    sb.append("    poBoxInput: ").append(toIndentedString(poBoxInput)).append("\n");
    sb.append("    privateMailboxInput: ").append(toIndentedString(privateMailboxInput)).append("\n");
    sb.append("    privateMailboxTypeInput: ").append(toIndentedString(privateMailboxTypeInput)).append("\n");
    sb.append("    cityInput: ").append(toIndentedString(cityInput)).append("\n");
    sb.append("    stateProvinceInput: ").append(toIndentedString(stateProvinceInput)).append("\n");
    sb.append("    postalCodeInput: ").append(toIndentedString(postalCodeInput)).append("\n");
    sb.append("    countryInput: ").append(toIndentedString(countryInput)).append("\n");
    sb.append("    firmNameInput: ").append(toIndentedString(firmNameInput)).append("\n");
    sb.append("    houseNumberResult: ").append(toIndentedString(houseNumberResult)).append("\n");
    sb.append("    leadingDirectionalResult: ").append(toIndentedString(leadingDirectionalResult)).append("\n");
    sb.append("    streetResult: ").append(toIndentedString(streetResult)).append("\n");
    sb.append("    streetNameResult: ").append(toIndentedString(streetNameResult)).append("\n");
    sb.append("    streetNameAliasType: ").append(toIndentedString(streetNameAliasType)).append("\n");
    sb.append("    streetSuffixResult: ").append(toIndentedString(streetSuffixResult)).append("\n");
    sb.append("    trailingDirectionalResult: ").append(toIndentedString(trailingDirectionalResult)).append("\n");
    sb.append("    apartmentLabelResult: ").append(toIndentedString(apartmentLabelResult)).append("\n");
    sb.append("    apartmentNumberResult: ").append(toIndentedString(apartmentNumberResult)).append("\n");
    sb.append("    apartmentLabel2Result: ").append(toIndentedString(apartmentLabel2Result)).append("\n");
    sb.append("    apartmentNumber2Result: ").append(toIndentedString(apartmentNumber2Result)).append("\n");
    sb.append("    rrHCResult: ").append(toIndentedString(rrHCResult)).append("\n");
    sb.append("    rrHCType: ").append(toIndentedString(rrHCType)).append("\n");
    sb.append("    poBoxResult: ").append(toIndentedString(poBoxResult)).append("\n");
    sb.append("    cityResult: ").append(toIndentedString(cityResult)).append("\n");
    sb.append("    stateProvinceResult: ").append(toIndentedString(stateProvinceResult)).append("\n");
    sb.append("    postalCodeResult: ").append(toIndentedString(postalCodeResult)).append("\n");
    sb.append("    postalCodeCityResult: ").append(toIndentedString(postalCodeCityResult)).append("\n");
    sb.append("    addressRecordResult: ").append(toIndentedString(addressRecordResult)).append("\n");
    sb.append("    postalCodeSource: ").append(toIndentedString(postalCodeSource)).append("\n");
    sb.append("    postalCodeType: ").append(toIndentedString(postalCodeType)).append("\n");
    sb.append("    countryResult: ").append(toIndentedString(countryResult)).append("\n");
    sb.append("    firmNameResult: ").append(toIndentedString(firmNameResult)).append("\n");
    sb.append("    streetNamePreferredAliasResult: ").append(toIndentedString(streetNamePreferredAliasResult)).append("\n");
    sb.append("    streetNameAbbreviatedAliasResult: ").append(toIndentedString(streetNameAbbreviatedAliasResult)).append("\n");
    sb.append("    addressLine5: ").append(toIndentedString(addressLine5)).append("\n");
    sb.append("    addressQuality: ").append(toIndentedString(addressQuality)).append("\n");
    sb.append("    deliverability: ").append(toIndentedString(deliverability)).append("\n");
    sb.append("    addressType: ").append(toIndentedString(addressType)).append("\n");
    sb.append("    locality: ").append(toIndentedString(locality)).append("\n");
    sb.append("    changeScore: ").append(toIndentedString(changeScore)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    blockAddress: ").append(toIndentedString(blockAddress)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

